---
abstract: 'A hierarchy of exceptions that can be used in many'
author:
  - 'Scott Yourstone <scott.yourstone81@gmail.com>'
build_requires:
  Exception::Class: '0'
  File::Basename: '0'
  File::Spec: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MyX-Generic
provides:
  MyX::Generic:
    file: lib/MyX/Generic.pm
    version: v0.0.3
requires:
  Test::More: '0'
  version: '0'
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.3
x_test_requires:
  File::Temp: '0'
  Test::Exception: '0'
  Test::More: '0'
  Test::Pod: '1.14'
  Test::Pod::Coverage: '1.04'
